dist: xenial
jobs:
  include:
    install: skip
    script:
      - ./.travis/run_optipng
      - ./.travis/zip_artifacts
    deploy:
      provider: releases
      api_key: "$BOT_AUTH_TOKEN"
      file_glob: true
      file: artifacts/*
      skip_cleanup: true
