#!/bin/bash


sudo apt install optipng
find . -name "*png" | head | xargs optipng -preserve -o7 {} 2>&1 | grep -iE "png|decrease|error|warn"

git config --global user.email "tripleabuilderbot@gmail.com"
git config --global user.name "tripleabuilderbot"
git commit . -m "Apply optipng compression on all png files"

echo "$BOT_AUTH_TOKEN" >> ~/.git-credentials
git config credential.helper store
git push -fq origin master



