#!/bin/bash


sudo apt install optipng
find . -name "*png" | head | xargs optipng -preserve -o7 {} 
# 2>&1 | grep -iE "png|decrease|error|warn"

git config --global user.email "tripleabuilderbot@gmail.com"
git config --global user.name "tripleabuilderbot"

git status
git branch -m master
git commit . -m "Apply optipng compression on all png files"

git status
git remote add repo "https://${BOT_AUTH_TOKEN}@github.com/DanVanAtta/test.git" &> /dev/null
git push --quiet --set-upstream repo master

