#!/bin/bash

sudo apt install optipng

git checkout  master
git config --global user.email "tripleabuilderbot@gmail.com"
git config --global user.name "tripleabuilderbot"


## find all PNG files, run lossless compression
## Filter output for errors, the line stating which file is being proccessed and percentage decrease
find . -name "*png" | head -150 | xargs optipng -preserve -o7 2>&1 | grep -iE "png|% decrease|error|warn"

## If any files are changed, we'll commit them here
## If we commit and push, that will trigger a new build.
## If we trigger a new build, terminate the current build so we avoid deploying artifacts
git commit . -m "Apply optipng compression on all png files" &&
(
  git remote add repo "https://${BOT_AUTH_TOKEN}@github.com/DanVanAtta/test.git" &> /dev/null
  git push --quiet --set-upstream repo master
  echo "Committed compressed files. Terminating current build to abort deployment"
  exit 1
)

